export interface Theme {
  id: string;
  name: string;
  category: 'Film' | 'Classic' | 'Pastel' | 'Y2K' | 'Gradient' | 'Ornate' | 'Neon';
  stripBg: string;
  outerBorder?: string;
  outerRadius?: string;
  stripPadding?: string;
  photoBorder: string;
  photoRadius: number;
  textColor: string;
  fontFamily?: string;
  letterSpacing?: string;
  filmStrip?: boolean;
  previewBg: string;
  // NEW: decorative corner / extra style props
  cornerDecor?: string;     // SVG data or CSS for corner ornaments
  innerGlow?: string;       // box-shadow inner glow
  stripOverlay?: string;    // pseudo overlay (gradient on top of photos)
}

export const THEMES: Theme[] = [
  // ── FILM ────────────────────────────────────────────────────────────────────
  {
    id: 'kodak-warm',
    name: 'Kodak Gold',
    category: 'Film',
    stripBg: '#faf3e0',
    outerBorder: '3px solid #c8a96e',
    outerRadius: '2px',
    photoBorder: '2px solid #c8a96e',
    photoRadius: 1,
    textColor: '#7c5a2e',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.18em',
    filmStrip: true,
    innerGlow: 'inset 0 0 24px rgba(200,169,110,0.12)',
    previewBg: '#f0d89a',
  },
  {
    id: 'film-noir',
    name: 'Noir',
    category: 'Film',
    stripBg: '#0f0f0f',
    outerBorder: '2px solid #3a3a3a',
    outerRadius: '0px',
    photoBorder: '2px solid #2e2e2e',
    photoRadius: 0,
    textColor: '#666666',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.22em',
    filmStrip: true,
    innerGlow: 'inset 0 0 40px rgba(0,0,0,0.7)',
    previewBg: '#1a1a1a',
  },
  {
    id: 'velvia',
    name: 'Velvia',
    category: 'Film',
    stripBg: '#07111f',
    outerBorder: '1px solid #1e3a5f',
    outerRadius: '0px',
    photoBorder: '2px solid #1d4b87',
    photoRadius: 0,
    textColor: '#3a80d9',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.15em',
    filmStrip: true,
    innerGlow: 'inset 0 0 40px rgba(10,22,60,0.6)',
    previewBg: '#0a1628',
  },
  {
    id: 'sepia-vintage',
    name: 'Sepia',
    category: 'Film',
    stripBg: '#f2e8d5',
    outerBorder: '8px double #c4a882',
    outerRadius: '2px',
    photoBorder: '3px solid #c4a882',
    photoRadius: 0,
    textColor: '#7a5c38',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.12em',
    filmStrip: true,
    innerGlow: 'inset 0 0 32px rgba(196,168,130,0.18)',
    previewBg: '#e8d5b2',
  },
  {
    id: 'agfa-vista',
    name: 'Agfa Vista',
    category: 'Film',
    stripBg: '#1a0a00',
    outerBorder: '3px solid #8B2500',
    outerRadius: '0px',
    photoBorder: '2px solid #6B1A00',
    photoRadius: 0,
    textColor: '#cc4400',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    filmStrip: true,
    innerGlow: 'inset 0 0 32px rgba(139,37,0,0.3)',
    previewBg: '#3d0f00',
  },
  {
    id: 'ilford',
    name: 'Ilford HP5',
    category: 'Film',
    stripBg: '#e8e8e6',
    outerBorder: '4px solid #888',
    outerRadius: '0px',
    photoBorder: '3px solid #999',
    photoRadius: 0,
    textColor: '#333333',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    filmStrip: true,
    innerGlow: 'inset 0 0 20px rgba(0,0,0,0.08)',
    previewBg: '#ccccca',
  },

  // ── CLASSIC ─────────────────────────────────────────────────────────────────
  {
    id: 'polaroid',
    name: 'Polaroid',
    category: 'Classic',
    stripBg: '#f9f9f7',
    outerBorder: '1px solid #e0ddd6',
    outerRadius: '4px',
    photoBorder: '10px solid #f5f5f0',
    photoRadius: 1,
    textColor: '#aaaaaa',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.08em',
    innerGlow: '0 8px 32px rgba(0,0,0,0.08)',
    previewBg: '#f0efea',
  },
  {
    id: 'studio-white',
    name: 'Studio',
    category: 'Classic',
    stripBg: '#ffffff',
    outerBorder: '2px solid #e0e0e0',
    outerRadius: '6px',
    photoBorder: '1px solid #e0e0e0',
    photoRadius: 4,
    textColor: '#b0b0b0',
    letterSpacing: '0.15em',
    innerGlow: '0 4px 24px rgba(0,0,0,0.06)',
    previewBg: '#f5f5f5',
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    category: 'Classic',
    stripBg: '#161616',
    outerBorder: '1.5px solid #2e2e2e',
    outerRadius: '8px',
    photoBorder: '1px solid #333',
    photoRadius: 6,
    textColor: '#444444',
    letterSpacing: '0.15em',
    innerGlow: 'inset 0 0 40px rgba(0,0,0,0.5)',
    previewBg: '#2a2a2a',
  },
  {
    id: 'linen',
    name: 'Linen',
    category: 'Classic',
    stripBg: '#f6f0e8',
    outerBorder: '4px solid #d4c5ae',
    outerRadius: '4px',
    photoBorder: '2px solid #d4c5ae',
    photoRadius: 2,
    textColor: '#9b7e5a',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.14em',
    innerGlow: 'inset 0 0 20px rgba(180,155,120,0.1)',
    previewBg: '#ecdccc',
  },

  // ── PASTEL ──────────────────────────────────────────────────────────────────
  {
    id: 'strawberry',
    name: 'Strawberry',
    category: 'Pastel',
    stripBg: '#fce4ec',
    outerBorder: '3px solid #f8bbd0',
    outerRadius: '16px',
    photoBorder: '4px solid #f48fb1',
    photoRadius: 10,
    textColor: '#ad1457',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.1em',
    innerGlow: 'inset 0 0 24px rgba(244,143,177,0.15)',
    previewBg: '#f8bbd0',
  },
  {
    id: 'matcha',
    name: 'Matcha',
    category: 'Pastel',
    stripBg: '#e8f5e9',
    outerBorder: '3px solid #a5d6a7',
    outerRadius: '12px',
    photoBorder: '4px solid #81c784',
    photoRadius: 8,
    textColor: '#2e7d32',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.1em',
    innerGlow: 'inset 0 0 24px rgba(129,199,132,0.12)',
    previewBg: '#c8e6c9',
  },
  {
    id: 'baby-blue',
    name: 'Baby Blue',
    category: 'Pastel',
    stripBg: '#e3f2fd',
    outerBorder: '3px solid #90caf9',
    outerRadius: '12px',
    photoBorder: '4px solid #64b5f6',
    photoRadius: 8,
    textColor: '#1565c0',
    letterSpacing: '0.12em',
    innerGlow: 'inset 0 0 24px rgba(100,181,246,0.12)',
    previewBg: '#bbdefb',
  },
  {
    id: 'butter',
    name: 'Butter',
    category: 'Pastel',
    stripBg: '#fffde7',
    outerBorder: '3px solid #ffe082',
    outerRadius: '12px',
    photoBorder: '4px solid #ffd54f',
    photoRadius: 8,
    textColor: '#f57f17',
    letterSpacing: '0.12em',
    innerGlow: 'inset 0 0 24px rgba(255,213,79,0.12)',
    previewBg: '#fff9c4',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    category: 'Pastel',
    stripBg: '#f3e5f5',
    outerBorder: '3px solid #ce93d8',
    outerRadius: '16px',
    photoBorder: '4px solid #ba68c8',
    photoRadius: 12,
    textColor: '#6a1b9a',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.08em',
    innerGlow: 'inset 0 0 24px rgba(186,104,200,0.12)',
    previewBg: '#e1bee7',
  },
  {
    id: 'peach-fuzz',
    name: 'Peach',
    category: 'Pastel',
    stripBg: '#fff3e0',
    outerBorder: '3px solid #ffcc80',
    outerRadius: '12px',
    photoBorder: '4px solid #ffb74d',
    photoRadius: 8,
    textColor: '#e65100',
    letterSpacing: '0.15em',
    innerGlow: 'inset 0 0 24px rgba(255,183,77,0.12)',
    previewBg: '#ffcc80',
  },
  {
    id: 'mint-choc',
    name: 'Mint Choc',
    category: 'Pastel',
    stripBg: '#e0f2f1',
    outerBorder: '4px solid #4db6ac',
    outerRadius: '12px',
    photoBorder: '4px solid #26a69a',
    photoRadius: 8,
    textColor: '#004d40',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.1em',
    innerGlow: 'inset 0 0 20px rgba(38,166,154,0.1)',
    previewBg: '#b2dfdb',
  },
  {
    id: 'rosewood',
    name: 'Rosewood',
    category: 'Pastel',
    stripBg: '#fce8e8',
    outerBorder: '3px solid #ef9a9a',
    outerRadius: '16px',
    photoBorder: '4px solid #e57373',
    photoRadius: 10,
    textColor: '#b71c1c',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.1em',
    previewBg: '#ffcdd2',
  },

  // ── Y2K ─────────────────────────────────────────────────────────────────────
  {
    id: 'arcade',
    name: 'Arcade',
    category: 'Y2K',
    stripBg: '#fef08a',
    outerBorder: '6px solid #000000',
    outerRadius: '6px',
    photoBorder: '3px solid #000000',
    photoRadius: 4,
    textColor: '#000000',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    previewBg: '#fef08a',
  },
  {
    id: 'candy-pop',
    name: 'Candy Pop',
    category: 'Y2K',
    stripBg: '#ff1493',
    outerBorder: '5px solid #ffffff',
    outerRadius: '24px',
    photoBorder: '6px solid #ffffff',
    photoRadius: 16,
    textColor: '#ffffff',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.1em',
    innerGlow: 'inset 0 0 32px rgba(255,105,180,0.4)',
    previewBg: '#ff69b4',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    category: 'Y2K',
    stripBg: 'linear-gradient(170deg, #0f0c29 0%, #302b63 100%)',
    outerBorder: '2px solid #ff71ce',
    outerRadius: '0px',
    photoBorder: '2px solid #ff71ce',
    photoRadius: 0,
    textColor: '#ff71ce',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    innerGlow: 'inset 0 0 40px rgba(255,113,206,0.15)',
    previewBg: '#302b63',
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    category: 'Y2K',
    stripBg: '#ffb3de',
    outerBorder: '5px dashed #ff69b4',
    outerRadius: '20px',
    photoBorder: '4px dashed #ff1493',
    photoRadius: 12,
    textColor: '#c2185b',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.08em',
    previewBg: '#ffb3de',
  },
  {
    id: 'matrix',
    name: 'Matrix',
    category: 'Y2K',
    stripBg: '#000000',
    outerBorder: '2px solid #00ff41',
    outerRadius: '0px',
    photoBorder: '2px solid #00cc33',
    photoRadius: 0,
    textColor: '#00ff41',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    innerGlow: 'inset 0 0 40px rgba(0,255,65,0.08)',
    previewBg: '#001a00',
  },

  // ── GRADIENT ────────────────────────────────────────────────────────────────
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    category: 'Gradient',
    stripBg: 'linear-gradient(170deg, #ffecd2 0%, #fcb69f 100%)',
    outerBorder: '3px solid rgba(252,182,159,0.8)',
    outerRadius: '12px',
    photoBorder: '4px solid rgba(255,255,255,0.7)',
    photoRadius: 10,
    textColor: '#b5451b',
    letterSpacing: '0.15em',
    innerGlow: '0 8px 40px rgba(252,100,50,0.2)',
    previewBg: 'linear-gradient(135deg, #ffecd2, #fcb69f)',
  },
  {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    category: 'Gradient',
    stripBg: 'linear-gradient(170deg, #1565c0 0%, #0d47a1 100%)',
    outerBorder: '3px solid rgba(100,181,246,0.5)',
    outerRadius: '12px',
    photoBorder: '4px solid rgba(255,255,255,0.4)',
    photoRadius: 10,
    textColor: '#ffffff',
    letterSpacing: '0.15em',
    innerGlow: 'inset 0 0 40px rgba(0,50,150,0.4)',
    previewBg: 'linear-gradient(135deg, #42a5f5, #0d47a1)',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    category: 'Gradient',
    stripBg: 'linear-gradient(170deg, #0d1b2a 0%, #1b2838 50%, #0a2240 100%)',
    outerBorder: '2px solid #00e5ff',
    outerRadius: '4px',
    photoBorder: '2px solid #00bcd4',
    photoRadius: 4,
    textColor: '#00e5ff',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.18em',
    innerGlow: 'inset 0 0 60px rgba(0,100,180,0.3)',
    previewBg: 'linear-gradient(135deg, #1a237e, #00bcd4)',
  },
  {
    id: 'sunset-dusk',
    name: 'Sunset',
    category: 'Gradient',
    stripBg: 'linear-gradient(170deg, #2d1b69 0%, #8b2fc9 50%, #e91e8c 100%)',
    outerBorder: '3px solid rgba(233,30,140,0.6)',
    outerRadius: '12px',
    photoBorder: '3px solid rgba(255,255,255,0.35)',
    photoRadius: 8,
    textColor: '#ff80ab',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.12em',
    innerGlow: 'inset 0 0 40px rgba(139,47,201,0.3)',
    previewBg: 'linear-gradient(135deg, #2d1b69, #e91e8c)',
  },
  {
    id: 'forest-mist',
    name: 'Forest',
    category: 'Gradient',
    stripBg: 'linear-gradient(170deg, #1b4332 0%, #2d6a4f 100%)',
    outerBorder: '3px solid rgba(82,183,136,0.5)',
    outerRadius: '12px',
    photoBorder: '3px solid rgba(255,255,255,0.3)',
    photoRadius: 8,
    textColor: '#95d5b2',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.15em',
    innerGlow: 'inset 0 0 40px rgba(27,67,50,0.5)',
    previewBg: 'linear-gradient(135deg, #1b4332, #52b788)',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    category: 'Gradient',
    stripBg: 'linear-gradient(170deg, #f8d7da 0%, #f5a9b4 50%, #e88396 100%)',
    outerBorder: '4px solid rgba(232,131,150,0.8)',
    outerRadius: '16px',
    photoBorder: '4px solid rgba(255,255,255,0.6)',
    photoRadius: 12,
    textColor: '#8b1a2e',
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: '0.12em',
    innerGlow: '0 8px 40px rgba(232,131,150,0.25)',
    previewBg: 'linear-gradient(135deg, #f8d7da, #e88396)',
  },

  // ── ORNATE ──────────────────────────────────────────────────────────────────
  {
    id: 'art-deco',
    name: 'Art Déco',
    category: 'Ornate',
    stripBg: '#1a1508',
    outerBorder: '6px double #c9a84c',
    outerRadius: '2px',
    stripPadding: '20px 18px 60px',
    photoBorder: '3px solid #c9a84c',
    photoRadius: 0,
    textColor: '#c9a84c',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.25em',
    innerGlow: 'inset 0 0 60px rgba(0,0,0,0.6), inset 0 0 20px rgba(201,168,76,0.08)',
    previewBg: 'linear-gradient(135deg, #1a1508, #3d2f00)',
  },
  {
    id: 'royal',
    name: 'Royal Blue',
    category: 'Ornate',
    stripBg: '#0c1445',
    outerBorder: '6px double #d4af37',
    outerRadius: '2px',
    stripPadding: '20px 18px 60px',
    photoBorder: '3px solid #d4af37',
    photoRadius: 0,
    textColor: '#d4af37',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    innerGlow: 'inset 0 0 60px rgba(0,0,80,0.6)',
    previewBg: 'linear-gradient(135deg, #0c1445, #1a237e)',
  },
  {
    id: 'victorian',
    name: 'Victorian',
    category: 'Ornate',
    stripBg: '#2c1810',
    outerBorder: '8px double #8b6241',
    outerRadius: '4px',
    stripPadding: '20px 18px 60px',
    photoBorder: '4px solid #8b6241',
    photoRadius: 2,
    textColor: '#c8a97e',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.15em',
    innerGlow: 'inset 0 0 60px rgba(44,24,16,0.8)',
    previewBg: 'linear-gradient(135deg, #2c1810, #5c3d1e)',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    category: 'Ornate',
    stripBg: '#0a1f0a',
    outerBorder: '5px double #2e8b57',
    outerRadius: '4px',
    stripPadding: '20px 18px 60px',
    photoBorder: '3px solid #2e8b57',
    photoRadius: 0,
    textColor: '#3cb371',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    innerGlow: 'inset 0 0 40px rgba(0,80,0,0.4)',
    previewBg: 'linear-gradient(135deg, #0a1f0a, #1a4a1a)',
  },
  {
    id: 'platinum',
    name: 'Platinum',
    category: 'Ornate',
    stripBg: '#f8f8f8',
    outerBorder: '4px double #b0b8c1',
    outerRadius: '4px',
    stripPadding: '20px 18px 60px',
    photoBorder: '3px solid #90a0b0',
    photoRadius: 2,
    textColor: '#708090',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    innerGlow: '0 8px 40px rgba(144,160,176,0.2)',
    previewBg: 'linear-gradient(135deg, #e8edf0, #c8d4dc)',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'Ornate',
    stripBg: '#0a0a0a',
    outerBorder: '6px double #444',
    outerRadius: '0px',
    stripPadding: '20px 18px 60px',
    photoBorder: '2px solid #333',
    photoRadius: 0,
    textColor: '#555555',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.25em',
    innerGlow: 'inset 0 0 80px rgba(0,0,0,0.8)',
    previewBg: '#0f0f0f',
  },

  // ── NEON ────────────────────────────────────────────────────────────────────
  {
    id: 'neon-pink',
    name: 'Neon Pink',
    category: 'Neon',
    stripBg: '#0a0010',
    outerBorder: '2px solid #ff00aa',
    outerRadius: '4px',
    photoBorder: '2px solid #cc0088',
    photoRadius: 4,
    textColor: '#ff00aa',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    innerGlow: 'inset 0 0 40px rgba(255,0,170,0.12), 0 0 20px rgba(255,0,170,0.3)',
    previewBg: 'linear-gradient(135deg, #1a0026, #3d0040)',
  },
  {
    id: 'neon-cyan',
    name: 'Neon Cyan',
    category: 'Neon',
    stripBg: '#000e14',
    outerBorder: '2px solid #00ffff',
    outerRadius: '4px',
    photoBorder: '2px solid #00cccc',
    photoRadius: 4,
    textColor: '#00ffff',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    innerGlow: 'inset 0 0 40px rgba(0,255,255,0.1), 0 0 20px rgba(0,255,255,0.3)',
    previewBg: 'linear-gradient(135deg, #001a26, #002040)',
  },
  {
    id: 'neon-orange',
    name: 'Neon Orange',
    category: 'Neon',
    stripBg: '#0f0500',
    outerBorder: '2px solid #ff6600',
    outerRadius: '4px',
    photoBorder: '2px solid #cc4400',
    photoRadius: 4,
    textColor: '#ff8800',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    innerGlow: 'inset 0 0 40px rgba(255,102,0,0.1), 0 0 20px rgba(255,102,0,0.3)',
    previewBg: 'linear-gradient(135deg, #1a0800, #331000)',
  },
  {
    id: 'neon-green',
    name: 'Neon Lime',
    category: 'Neon',
    stripBg: '#040d00',
    outerBorder: '2px solid #aaff00',
    outerRadius: '4px',
    photoBorder: '2px solid #88cc00',
    photoRadius: 4,
    textColor: '#aaff00',
    fontFamily: "'DM Mono', monospace",
    letterSpacing: '0.2em',
    innerGlow: 'inset 0 0 40px rgba(170,255,0,0.08), 0 0 20px rgba(170,255,0,0.25)',
    previewBg: 'linear-gradient(135deg, #0a1a00, #142800)',
  },
];

export const THEME_CATEGORIES = ['All', 'Film', 'Classic', 'Pastel', 'Y2K', 'Gradient', 'Ornate', 'Neon'] as const;
export type ThemeCategory = typeof THEME_CATEGORIES[number];